name: Run

on:
  [ push, pull_request, workflow_dispatch ]
  
jobs:

  main:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3.0.2
      with:
        submodules: 'true'

    - name: Build
      run: dotnet build -c Release

    - name: Download Server
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: |
        mkdir -p SDK/Tools/Server
        curl -L -o SDK/Tools/Server/server.zip https://minecraft.azureedge.net/bin-win/bedrock-server-1.19.41.01.zip
        unzip SDK/Tools/Server/server.zip -d SDK/Tools/Server/ > /dev/null

    - name: Build Library
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        cd SDK\Tools
        LibraryBuilder.exe -o ..\Lib Server

    - name: Run
      run: LibraryGenerator\bin\Release\net6.0\LibraryGenerator.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: artifact
        path: output
